/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M9
 * Generated at: 2020-03-13 04:15:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\t<title>JSP AJAX</title>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar searchRequest = new XMLHttpRequest();\r\n");
      out.write("\t\tvar registerRequest = new XMLHttpRequest();\r\n");
      out.write("\t\tfunction searchFunction(){\r\n");
      out.write("\t\t\tsearchRequest.open(\"Post\", \"./UserSearchServlet?userName=\" + encodeURIComponent(document.getElementById(\"userName\").value), true);\r\n");
      out.write("\t\t\tsearchRequest.onreadystatechange = searchProcess;\r\n");
      out.write("\t\t\tsearchRequest.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction searchProcess(){\r\n");
      out.write("\t\t\tvar table = document.getElementById(\"ajaxTable\");\r\n");
      out.write("\t\t\ttable.innerHTML = \"\";\r\n");
      out.write("\t\t\tif(searchRequest.readyState = 4 && searchRequest.status == 200) {\r\n");
      out.write("\t\t\t\tvar object = eval('(' + searchRequest.responseText + ')');\r\n");
      out.write("\t\t\t\tvar result = object.result;\r\n");
      out.write("\t\t\t\tfor(var i = 0; i < result.length; i++){\r\n");
      out.write("\t\t\t\t\tvar row = table.insertRow(0);\r\n");
      out.write("\t\t\t\t\tfor(var j = 0; j < result[i].length; j++){\r\n");
      out.write("\t\t\t\t\t\tvar cell = row.insertCell(j);\r\n");
      out.write("\t\t\t\t\t\tcell.innerHTML = result[i][j].value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar registerName = document.getElementById(\"registerName\");\r\n");
      out.write("\t\t\tvar registerAge = document.getElementById(\"registerAge\");\r\n");
      out.write("\t\t\tvar registerEmail = document.getElementById(\"registerEmail\");\r\n");
      out.write("\t\t\tregisterName.value =\"\";\r\n");
      out.write("\t\t\tregisterAge.value = \"\";\r\n");
      out.write("\t\t\tregisterEmail.value = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction registerFunction(){\r\n");
      out.write("\t\t\tregisterRequest.open(\"Post\", \"./UserRegisterServlet?userName=\" + encodeURIComponent(document.getElementById(\"registerName\").value) +\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"&userAge=\" + encodeURIComponent(document.getElementById(\"registerAge\").value) +\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"&userGender=\" + encodeURIComponent($('input[name=registerGender]:checked').val()) +\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"&userEmail=\" + encodeURIComponent(document.getElementById(\"registerEmail\").value), true);\r\n");
      out.write("\t\t\tregisterRequest.onreadystatechange = registerProcess;\r\n");
      out.write("\t\t\tregisterRequest.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction registerProcess(){\r\n");
      out.write("\t\t\tif(registerRequest.readyState == 4 && registerRequest.status == 200){\r\n");
      out.write("\t\t\t\tvar result = registerRequest.responseText;\r\n");
      out.write("\t\t\t\tif(result != 1){\r\n");
      out.write("\t\t\t\t\talert('등록에 실패했습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\tvar userName = document.getElementById(\"userName\");\r\n");
      out.write("\t\t\t\t\tvar registerName = document.getElementById(\"registerName\");\r\n");
      out.write("\t\t\t\t\tvar registerAge = document.getElementById(\"registerAge\");\r\n");
      out.write("\t\t\t\t\tvar registerEmail = document.getElementById(\"registerEmail\");\r\n");
      out.write("\t\t\t\t\tuserName.value = \"\";\r\n");
      out.write("\t\t\t\t\tregisterName.value =\"\";\r\n");
      out.write("\t\t\t\t\tregisterAge.value = \"\";\r\n");
      out.write("\t\t\t\t\tregisterEmail.value = \"\";\r\n");
      out.write("\t\t\t\t\tsearchFunction();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\twindow.onload = searchFunction;\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class = \"container\">\r\n");
      out.write("\t\t<div class=\"form-group row pull-right\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t<input class=\"form=control\" id=\"userName\" onkeyup=\"searchFunction()\" type=\"text\" size=\"20\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\" type=\"button\" onclick=\"searchFunction();\">검색</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table class=\"table\" style=\"text-align: center; border: 1px solid #dddddd\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color: #fafafa; text-align: center;\">이름</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color: #fafafa; text-align: center;\">나이</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color: #fafafa; text-align: center;\">성별</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"background-color: #fafafa; text-align: center;\">이메일</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody id=\"ajaxTable\">\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<table class=\"table\" style=\"text-align: enter; border: 1px solid #dddddd\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" style=\"background-color: #fafafa; text-align: center;\">회원 등록 양식</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color:#fafafa; text-align:center;\"><h5>이름</h5></td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"form-control\" type=\"text\" id=\"registerName\" size=\"20\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color:#fafafa; text-align:center;\"><h5>나이</h5></td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"form-control\" type=\"text\" id=\"registerAge\" size=\"20\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color:#fafafa; text-align:center;\"><h5>성별</h5></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" style=\"text-align: center; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"btn btn-primary active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"registerGender\" autocomplete=\"off\" value=\"남자\" checked>남자\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"registerGender\" autocomplete=\"off\" value=\"여자\">여자\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color:#fafafa; text-align:center;\"><h5>이메일</h5></td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"form-control\" type=\"text\" id=\"registerEmail\" size=\"20\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"><button class=\"btn btn-primary pull-right\" onclick=\"registerFunction();\" type=\"button\">등록</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
